name: Bowinc Publish to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
   
   cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build PHP BOWINC CLI and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: aohycent/bowinc-php
          tags: "main"
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: Dockerfile



