name: Testrun

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: PHP testing actions

        uses: aohycent/bowinc-php

        with:

          args: php -v && php -m
