name: Testrun

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: BOWINC php actions

        uses: aohycent/bowinc-php@main

        with:

          args: php -v && php -m
